### ISSUE TITLE
Data Imputation

### ISSUE THREAD

**Issue by C-Inzirillo** [course-dprep/actor_diversity_film_industry#25]
### Check whether there are missing values and replace them (tip: using filter, group by and summarize)
**Use these lines of code as an example**

# input
df <- read_csv("df_no_duplicates.csv")

# transformation
imputation_values <- df %>% filter(!is.na(popularity)) %>% 
  group_by(country, date) %>% 
  summarise(popularity_filled = median(popularity))

df_joined <- df %>% left_join(imputation_values, by = c("country" = "country", "date" = "date"))

df <- df_joined %>% mutate(popularity_filled = ifelse(is.na(popularity), popularity_filled, popularity))

# output
write_csv(df, "df_imputed.csv")

**Comment by a-reyhan** [comment]
Not relevant anymore.
